/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SpBlePeripheral {}
  interface SpBlePeripheralAttributes extends StencilHTMLAttributes {
    'onBlePeripheralSelected'?: (event: CustomEvent) => void;
  }

  interface SpMidi {}
  interface SpMidiAttributes extends StencilHTMLAttributes {
    'onMidiOutputSelected'?: (event: CustomEvent) => void;
  }

  interface SpNotMidiBle {}
  interface SpNotMidiBleAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SpBlePeripheral': Components.SpBlePeripheral;
    'SpMidi': Components.SpMidi;
    'SpNotMidiBle': Components.SpNotMidiBle;
  }

  interface StencilIntrinsicElements {
    'sp-ble-peripheral': Components.SpBlePeripheralAttributes;
    'sp-midi': Components.SpMidiAttributes;
    'sp-not-midi-ble': Components.SpNotMidiBleAttributes;
  }


  interface HTMLSpBlePeripheralElement extends Components.SpBlePeripheral, HTMLStencilElement {}
  var HTMLSpBlePeripheralElement: {
    prototype: HTMLSpBlePeripheralElement;
    new (): HTMLSpBlePeripheralElement;
  };

  interface HTMLSpMidiElement extends Components.SpMidi, HTMLStencilElement {}
  var HTMLSpMidiElement: {
    prototype: HTMLSpMidiElement;
    new (): HTMLSpMidiElement;
  };

  interface HTMLSpNotMidiBleElement extends Components.SpNotMidiBle, HTMLStencilElement {}
  var HTMLSpNotMidiBleElement: {
    prototype: HTMLSpNotMidiBleElement;
    new (): HTMLSpNotMidiBleElement;
  };

  interface HTMLElementTagNameMap {
    'sp-ble-peripheral': HTMLSpBlePeripheralElement
    'sp-midi': HTMLSpMidiElement
    'sp-not-midi-ble': HTMLSpNotMidiBleElement
  }

  interface ElementTagNameMap {
    'sp-ble-peripheral': HTMLSpBlePeripheralElement;
    'sp-midi': HTMLSpMidiElement;
    'sp-not-midi-ble': HTMLSpNotMidiBleElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
